language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: nightly
install:
  - pip install .
  - pip install coveralls
script:
  - coverage run setup.py pytest
after_success:
  - coveralls
